#! /bin/bash

echo -e "\n################################################################################"
echo "# ANSI colors"
echo -e "################################################################################\n"

echo '  \033[0;x   \033[1;x    x = *m value'

for a in {30..37}
  do echo -e "    \033[0;${a}m${a}m        \033[1;${a}m${a}m"
done

echo -e "\033[0m"
echo  '  No color = \033[0;0m'

echo -e "\n################################################################################"
echo "# 256 colors"
echo -e "################################################################################\n"

echo '  \033[38;5;x    x = *m value'
echo ""

# 0-15
for a in {0..15}
  do echo -en "  \033[38;5;${a}m${a}m"
done

echo -e "  \033[m\n"

# 16-51
for a in {16..51}
  do echo -e "  \033[38;5;${a}m${a}m"
done

echo -e "  \033[m"
echo  '  No color = \033[m'

#for a in {0..6}
#  do let "a=a*36+16"
#  printf " %b" $a
#  for b in {0..35}
#    do let "c=a+b"
#    echo -en " $c \n"
#  done
#done

#for b in {0..6}
#let "b=b*36+16"
#let "c=a+b"
#echo -en "$c"
#done
#done

# for a in {0..23}
#    do let "b=a+16"
#    echo -e " $b "
#done

#for a in {0..6}
#    do let "b=a*36+16"
#    echo -en " $b"
#done
#done

# (16 52 88 124 160 196 232) x 16

# 16-231
#for a in {1..15}
#    do echo -e "$a "
#for b in {0..10}
#do let "c=$a+16+10*$b"
#echo -en "$c "
#done
#done

echo -e "\n################################################################################"
echo "# Note: both were tested on the terminal: xterm-256color"
echo '# Check with $TERM'
echo -e "################################################################################\n"
