#! /bin/bash

# To get latest version:
# git clone git@github.com:vim/vim.git
# ./configure
# make
# make install
#
# cp -r runtime/doc ~/vim_docs

# User manual
cat usr_01.txt usr_02.txt usr_03.txt usr_04.txt usr_05.txt usr_06.txt usr_07.txt usr_08.txt usr_09.txt usr_10.txt usr_11.txt usr_12.txt > um_01_getting_started.txt

cat usr_20.txt usr_21.txt usr_22.txt usr_23.txt usr_24.txt usr_25.txt usr_26.txt usr_27.txt usr_28.txt usr_29.txt usr_30.txt usr_31.txt usr_32.txt > um_02_editing_effectively.txt

cat usr_40.txt usr_41.txt usr_42.txt usr_43.txt usr_44.txt usr_45.txt > um_03_tuning_vim.txt

cp usr_90.txt um_04_making_vim_run.txt

# Reference manual
cat intro.txt help.txt helphelp.txt index.txt howto.txt tips.txt message.txt quotes.txt todo.txt develop.txt debug.txt uganda.txt > rm_01_general_subjects.txt

cat starting.txt editing.txt motion.txt scroll.txt insert.txt change.txt indent.txt undo.txt repeat.txt visual.txt various.txt recover.txt > rm_02_basic_editing.txt

cat cmdline.txt options.txt pattern.txt map.txt tagsrch.txt quickfix.txt windows.txt tabpage.txt syntax.txt spell.txt diff.txt diff.txt autocmd.txt filetype.txt eval.txt channel.txt fold.txt > rm_03_advanced_editing.txt

cat print.txt remote.txt term.txt digraph.txt mbyte.txt mlang.txt arabic.txt farsi.txt hebrew.txt russian.txt ft_ada.txt ft_sql.txt hangulin.txt rileft.txt > rm_04_special_issues.txt

cat gui.txt gui_w32.txt gui_x11.txt > rm_05_gui.txt

cat if_cscop.txt if_lua.txt if_mzsch.txt if_perl.txt if_pyth.txt if_tcl.txt if_ole.txt if_ruby.txt debugger.txt workshop.txt netbeans.txt sign.txt > rm_06_interfaces.txt

cat vi_diff.txt version4.txt version5.txt version6.txt version7.txt version8.txt > rm_07_versions.txt

cat os_390.txt os_amiga.txt os_beos.txt os_mac.txt os_mint.txt os_msdos.txt os_os2.txt os_qnx.txt os_risc.txt os_unix.txt os_vms.txt os_win32.txt > rm_08_remarks_about_specific_systems.txt

cat pi_getscript.txt pi_gzip.txt pi_logipat.txt pi_netrw.txt pi_tar.txt pi_vimball.txt pi_zip.txt > rm_09_standard_plugins.txt

