#!/bin/bash

# search online at brother's website for printer model and follow download link from there
# http://support.brother.com/g/b/downloadend.aspx?c=us&lang=en&prod=hll2340dw_us_eu_as&os=127&dlid=dlf006893_000&flang=4&type3=625

su -

echo "Enter user"
read USER

cd /home/$USER/Downloads/
chmod +x linux-brprinter-installer-2.1.1-1
yum install -y linux-brprinter-installer-2.1.1-1

exit

# model name:HL-L2340DW
# when prompted, say yes
# configure by IP address (7): 192.168.1.132

# if that doesn't work, follow instructions on website and uncomment lines below:

# cd /home/$USER/Downloads/
# gunzip linux-brprinter-installer-2.1.1-1.gz
# bash linux-brprinter-installer-2.1.1-1 HL-L2340DW
