#!/bin/bash

echo 'Enter user' 
read USER
cd /home/$USER/

wget -P /home/$USER/ https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh
bash Anaconda3-4.4.0-Linux-x86_64.sh
rm Anaconda3*.sh

# https://www.continuum.io/downloads#linux
# do not heed warning - allow the path variable to change
