#!/bin/bash

su -

echo "Enter user"
read $USER
if [ -d "/home/$USER/rpm/" ]
then
	cd /home/$USER/rpm/
else
	mkdir /home/$USER/rpm
	cd /home/$USER/rpm/
fi

wget -P /home/$USER/rpm/ http://mirror.centos.org/centos/7/os/x86_64/Packages/texinfo-tex-5.1-4.el7.x86_64.rpm
wget -P /home/$USER/rpm/ http://mirror.centos.org/centos/7/os/x86_64/Packages/texlive-epsf-doc-svn21461.2.7.4-38.el7.noarch.rpm
wget -P /home/$USER/rpm/ http://mirror.centos.org/centos/7/os/x86_64/Packages/texlive-epsf-svn21461.2.7.4-38.el7.noarch.rpm

# you may need to install the latest epel release as well
yum localinstall -y texlive-epsf-doc-svn21461.2.7.4-38.el7.noarch.rpm
yum localinstall -y texlive-epsf-svn21461.2.7.4-38.el7.noarch.rpm
yum localinstall -y texinfo-tex-5.1-4.el7.x86_64.rpm

yum install -y R
wget -P /home/$USER/rpm/ https://download1.rstudio.org/rstudio-1.0.143-x86_64.rpm
yum install -y rstudio-1.0.143-x86_64.rpm

exit

# R = https://cran.rstudio.com/
# RStudio = https://www.rstudio.com/products/rstudio/download/
# EPEL FAQ = https://fedoraproject.org/wiki/EPEL/FAQ#How_can_I_install_the_packages_from_the_EPEL_software_repository.3F
# help = https://superuser.com/questions/841270/installing-r-on-rhel-7
